name: NPM Publish

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  NODE_VERSION: 16
  #NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Python setuptools
        # Reasoning for this in `ci.yml`
        run: |
          python3 -m venv CI_venv
          source CI_venv/bin/activate
          python3 -m pip install setuptools
      - name: Install Dependencies
        run: |
          source CI_venv/bin/activate
          npm ci
      - run: |
          npm run test:node
          npm run test:native

  # publish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm publish --access public
